package com.company;

/**
 * Question : The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?

 Answer : 76576500
 */

public class Twelve {

    public static void main(String[] args) {
        // write your code here

        System.out.println("Triangle number which has more than five factors = " + getTriangleNumber());
    }

    static long getTriangleNumber() {

        long Tnumber = 0;
        long position = 1;

        while (true) {

            for (long i = 1; i <= position; i++) {
                Tnumber = Tnumber + i;
            }

            long numberOfDividers = getDividers(Tnumber);

            if (numberOfDividers >= 500) {
                break;
            }

            Tnumber = 0;
            position++;
        }

        return Tnumber;
    }

    static long getDividers(long triangleNumber) {

        long sumOfFactors = 0;
        for (long j = 1; j <= triangleNumber; j++) {

            if (triangleNumber % j == 0) {
                sumOfFactors++;
            }
        }
        return sumOfFactors;
    }
}
